public class Class01 {

    public static void main(String[] args) {

        //V1 çalışmalarım...
        //V2 çalışmalarım...
        //V3 çalışmalarım...
        //V4 çalışmalarım...
        //V5 çalışmalarım...
        //V6 çalışmalarım...
        //V7 çalışmalarım...
        //V8 çalışmalarım...
        //gitHub değişiklikleri   
        //Local den sevgiler...







    }//MAIN
}//CLASS
